version: "2"
services:
  # BULK SERVERS
  ns-init-1:
    image: "registry.americasreadiness.com:5000/ns-init"
    environment:
      - NSIP=${NSIP1}
      - SNIP=${SNIP1}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - VIP1=${SSL_VIP1_NS1}
      - VIP2=${HTTP_VIP1_NS1}
      - VIP3=${HTTP_VIP2_NS1}
      - VSERVER=${SSL_APP1_NS1}
      - VSERVER1=${HTTP_APP1_NS1}
      - VSERVER2=${HTTP_APP2_NS1}
      - HOSTNAME=${NS1}
      - DNS=${DNS}
      - DOCKERHOST=${WEBAPP_1}
      - SERVICE=srvc_backend-http-webapp-1
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "1"
    networks:
      SNIPS:
    hostname: ns-init-1
  
  ns-init-2:
    image: "registry.americasreadiness.com:5000/ns-init"
    environment:
      - NSIP=${NSIP1}
      - SNIP=${SNIP1}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - VIP1=${SSL_VIP2_NS1}
      - VIP2=${HTTP_VIP3_NS1}
      - VIP3=${HTTP_VIP4_NS1}
      - VSERVER=${SSL_APP2_NS1}
      - VSERVER1=${HTTP_APP3_NS1}
      - VSERVER2=${HTTP_APP4_NS1}
      - HOSTNAME=${NS1}
      - DNS=${DNS}
      - DOCKERHOST=${WEBAPP_2}
      - SERVICE=srvc_backend-http-webapp-2
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "1"
    networks:
      SNIPS:
    hostname: ns-init-2

  ns-init-3:
    image: "registry.americasreadiness.com:5000/ns-init"
    environment:
      - NSIP=${NSIP2}
      - SNIP=${SNIP2}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - VIP1=${SSL_VIP1_NS2}
      - VIP2=${HTTP_VIP1_NS2}
      - VIP3=${HTTP_VIP2_NS2}
      - VSERVER=${SSL_APP1_NS2}
      - VSERVER1=${HTTP_APP1_NS2}
      - VSERVER2=${HTTP_APP2_NS2}
      - HOSTNAME=${NS1}
      - DNS=${DNS}
      - DOCKERHOST=${WEBAPP_3}
      - SERVICE=srvc_backend-http-webapp-3
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "1"
    networks:
      SNIPS:
    hostname: ns-init-3

  ns-init-4:
    image: "registry.americasreadiness.com:5000/ns-init"
    environment:
      - NSIP=${NSIP2}
      - SNIP=${SNIP2}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - VIP1=${SSL_VIP2_NS2}
      - VIP2=${HTTP_VIP3_NS2}
      - VIP3=${HTTP_VIP4_NS2}
      - VSERVER=${SSL_APP2_NS2}
      - VSERVER1=${HTTP_APP3_NS2}
      - VSERVER2=${HTTP_APP4_NS2}
      - HOSTNAME=${NS1}
      - DNS=${DNS}
      - DOCKERHOST=${WEBAPP_4}
      - SERVICE=srvc_backend-http-webapp-4
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "1"
    networks:
      SNIPS:
    hostname: ns-init-4

networks:
  # define a host-external network 
  SNIPS:
    driver: macvlan
    driver_opts:
      parent: ${SNIP_ETH}
    ipam:
      config:
        - subnet: ${SNIP_NTW}
          gateway: ${SNIP_GW}
          ip_range: ${SNIP_RANGE} # IP from this pool are assigned automatically if no IP is specified